name: Generate Pac-Man Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allows pushing to output branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pac-Man graph
        uses: yoshi389111/github-profile-3d-contrib@v1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: vaibhavmishra03
          SETTINGS: pacman

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

