name: Generate Pac-Man Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch: # allow manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pac-Man graph
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          user: vaibhavmishra03
          output: dist/pacman-contribution-graph.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
